title: "Living Documentation"
description: docs with easy to click edit buttons
url: https://researchapps.github.io/living-docs
repo: http://github.com/researchapps/living-docs
theme: jekyll-theme-minimal
